spring:
  datasource :
    url : jdbc:mysql://localhost:3306/apply-job
    username : root
    password : root

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true


  mail :
     host : smtp.gmail.com
     port : 587
     username : krushnalilhare2998@gmail.com
     password : pkckcsljxvpjiaes
     properties :
        mail :
           smtp :
              auth : true
              starttls :
                enable: true




